ALTER TABLE "historical_data" ALTER COLUMN "date" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "open" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "high" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "low" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "close" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "volume" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "historical_data" ALTER COLUMN "adjustedClose" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "twoHundredDayAverage" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "twoHundredDayAverageChange" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "twoHundredDayAverageChangePercent" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "marketCap" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketChange" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketChangePercent" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketPrice" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketDayHigh" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketDayLow" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketVolume" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketPreviousClose" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "regularMarketOpen" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "averageDailyVolume3Month" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "averageDailyVolume10Day" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekLowChange" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekLowChangePercent" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekHighChange" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekHighChangePercent" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekLow" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "fiftyTwoWeekHigh" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "priceEarnings" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "tickers" ALTER COLUMN "earningsPerShare" SET DATA TYPE real;--> statement-breakpoint
ALTER TABLE "timestamps" ALTER COLUMN "date" SET DATA TYPE real;